vich_uploader:
    db_driver: orm

    mappings:
        card_image:
            uri_prefix: /uploads/cards
            upload_destination: '%kernel.project_dir%/public/uploads/cards'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true